package com.en.room.repository;

import com.en.room.entity.Landlord;

public interface LandlordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_landlord
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int deleteByPrimaryKey(Integer l_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_landlord
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insert(Landlord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_landlord
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insertSelective(Landlord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_landlord
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    Landlord selectByPrimaryKey(Integer l_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_landlord
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeySelective(Landlord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_landlord
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKey(Landlord record);
}