package com.en.room.repository;

import com.en.room.entity.News;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int deleteByPrimaryKey(Integer n_i_d);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    News selectByPrimaryKey(Integer n_i_d);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_news
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKey(News record);
}