package com.en.room.repository;

import com.en.room.entity.PicInfo;

public interface PicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_pic_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int deleteByPrimaryKey(Integer r_p_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_pic_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insert(PicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_pic_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insertSelective(PicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_pic_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    PicInfo selectByPrimaryKey(Integer r_p_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_pic_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeySelective(PicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_pic_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKey(PicInfo record);
}