package com.en.room.repository;

import com.en.room.entity.RoomDetail;

public interface RoomDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int deleteByPrimaryKey(Integer r_d_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insert(RoomDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insertSelective(RoomDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    RoomDetail selectByPrimaryKey(Integer r_d_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeySelective(RoomDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(RoomDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_detail
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKey(RoomDetail record);
}