package com.en.room.repository;

import com.en.room.entity.RoomBaseInfo;

public interface RoomBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_base_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int deleteByPrimaryKey(Integer r_b_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_base_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insert(RoomBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_base_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int insertSelective(RoomBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_base_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    RoomBaseInfo selectByPrimaryKey(Integer r_b_i);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_base_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKeySelective(RoomBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table en_room_base_info
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    int updateByPrimaryKey(RoomBaseInfo record);
}