package com.en.room.entity;

import java.util.Date;

public class Admin extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.aid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer a_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.loginname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String l_g_n;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.apwd
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String a_p_w;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.aname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String a_n_a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.createtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date c_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.astatus
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Byte a_s_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_admin.logintime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date l_g_t;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.aid
     *
     * @return the value of en_admin.aid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getA_i() {
        return a_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.aid
     *
     * @param a_i the value for en_admin.aid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_i(Integer a_i) {
        this.a_i = a_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.loginname
     *
     * @return the value of en_admin.loginname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getL_g_n() {
        return l_g_n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.loginname
     *
     * @param l_g_n the value for en_admin.loginname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_g_n(String l_g_n) {
        this.l_g_n = l_g_n == null ? null : l_g_n.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.apwd
     *
     * @return the value of en_admin.apwd
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getA_p_w() {
        return a_p_w;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.apwd
     *
     * @param a_p_w the value for en_admin.apwd
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_p_w(String a_p_w) {
        this.a_p_w = a_p_w == null ? null : a_p_w.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.aname
     *
     * @return the value of en_admin.aname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getA_n_a() {
        return a_n_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.aname
     *
     * @param a_n_a the value for en_admin.aname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_n_a(String a_n_a) {
        this.a_n_a = a_n_a == null ? null : a_n_a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.createtime
     *
     * @return the value of en_admin.createtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getC_t() {
        return c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.createtime
     *
     * @param c_t the value for en_admin.createtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_t(Date c_t) {
        this.c_t = c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.astatus
     *
     * @return the value of en_admin.astatus
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Byte getA_s_t() {
        return a_s_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.astatus
     *
     * @param a_s_t the value for en_admin.astatus
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_s_t(Byte a_s_t) {
        this.a_s_t = a_s_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_admin.logintime
     *
     * @return the value of en_admin.logintime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getL_g_t() {
        return l_g_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_admin.logintime
     *
     * @param l_g_t the value for en_admin.logintime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_g_t(Date l_g_t) {
        this.l_g_t = l_g_t;
    }
}