package com.en.room.entity;


public class Landlord extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_landlord.lid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer l_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_landlord.lname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String l_n_a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_landlord.llogo
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String l_l_o;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_landlord.llanguage
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String l_l_a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_landlord.lintroduce
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String l_i_n;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_landlord.lid
     *
     * @return the value of en_landlord.lid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getL_i() {
        return l_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_landlord.lid
     *
     * @param l_i the value for en_landlord.lid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_i(Integer l_i) {
        this.l_i = l_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_landlord.lname
     *
     * @return the value of en_landlord.lname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getL_n_a() {
        return l_n_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_landlord.lname
     *
     * @param l_n_a the value for en_landlord.lname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_n_a(String l_n_a) {
        this.l_n_a = l_n_a == null ? null : l_n_a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_landlord.llogo
     *
     * @return the value of en_landlord.llogo
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getL_l_o() {
        return l_l_o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_landlord.llogo
     *
     * @param l_l_o the value for en_landlord.llogo
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_l_o(String l_l_o) {
        this.l_l_o = l_l_o == null ? null : l_l_o.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_landlord.llanguage
     *
     * @return the value of en_landlord.llanguage
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getL_l_a() {
        return l_l_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_landlord.llanguage
     *
     * @param l_l_a the value for en_landlord.llanguage
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_l_a(String l_l_a) {
        this.l_l_a = l_l_a == null ? null : l_l_a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_landlord.lintroduce
     *
     * @return the value of en_landlord.lintroduce
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getL_i_n() {
        return l_i_n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_landlord.lintroduce
     *
     * @param l_i_n the value for en_landlord.lintroduce
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_i_n(String l_i_n) {
        this.l_i_n = l_i_n == null ? null : l_i_n.trim();
    }
}