package com.en.room.entity;

import java.util.Date;

public class ManagerLog extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_manager_log.mlid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer m_l_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_manager_log.loginname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String l_o_n;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_manager_log.aid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer a_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_manager_log.mtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date m_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_manager_log.mtable
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String m_t_a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_manager_log.mcontent
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String m_c_o;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_manager_log.mlid
     *
     * @return the value of en_manager_log.mlid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getM_l_i() {
        return m_l_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_manager_log.mlid
     *
     * @param m_l_i the value for en_manager_log.mlid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setM_l_i(Integer m_l_i) {
        this.m_l_i = m_l_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_manager_log.loginname
     *
     * @return the value of en_manager_log.loginname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getL_o_n() {
        return l_o_n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_manager_log.loginname
     *
     * @param l_o_n the value for en_manager_log.loginname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_o_n(String l_o_n) {
        this.l_o_n = l_o_n == null ? null : l_o_n.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_manager_log.aid
     *
     * @return the value of en_manager_log.aid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getA_i() {
        return a_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_manager_log.aid
     *
     * @param a_i the value for en_manager_log.aid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_i(Integer a_i) {
        this.a_i = a_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_manager_log.mtime
     *
     * @return the value of en_manager_log.mtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getM_t() {
        return m_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_manager_log.mtime
     *
     * @param m_t the value for en_manager_log.mtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setM_t(Date m_t) {
        this.m_t = m_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_manager_log.mtable
     *
     * @return the value of en_manager_log.mtable
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getM_t_a() {
        return m_t_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_manager_log.mtable
     *
     * @param m_t_a the value for en_manager_log.mtable
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setM_t_a(String m_t_a) {
        this.m_t_a = m_t_a == null ? null : m_t_a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_manager_log.mcontent
     *
     * @return the value of en_manager_log.mcontent
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getM_c_o() {
        return m_c_o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_manager_log.mcontent
     *
     * @param m_c_o the value for en_manager_log.mcontent
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setM_c_o(String m_c_o) {
        this.m_c_o = m_c_o == null ? null : m_c_o.trim();
    }
}