package com.en.room.entity;

import java.util.Date;

public class News extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.nid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer n_i_d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.title
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String t_i_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.intro
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String i_n_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.pushtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date p_u_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date c_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.ntype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Short n_t_y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.diid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Short d_i_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.district
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String d_i_s;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.isdel
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Byte i_s_d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_news.content
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String c_o_n;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.nid
     *
     * @return the value of en_news.nid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getN_i_d() {
        return n_i_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.nid
     *
     * @param n_i_d the value for en_news.nid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setN_i_d(Integer n_i_d) {
        this.n_i_d = n_i_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.title
     *
     * @return the value of en_news.title
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getT_i_t() {
        return t_i_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.title
     *
     * @param t_i_t the value for en_news.title
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setT_i_t(String t_i_t) {
        this.t_i_t = t_i_t == null ? null : t_i_t.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.intro
     *
     * @return the value of en_news.intro
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getI_n_t() {
        return i_n_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.intro
     *
     * @param i_n_t the value for en_news.intro
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setI_n_t(String i_n_t) {
        this.i_n_t = i_n_t == null ? null : i_n_t.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.pushtime
     *
     * @return the value of en_news.pushtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getP_u_t() {
        return p_u_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.pushtime
     *
     * @param p_u_t the value for en_news.pushtime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setP_u_t(Date p_u_t) {
        this.p_u_t = p_u_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.ctime
     *
     * @return the value of en_news.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getC_t() {
        return c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.ctime
     *
     * @param c_t the value for en_news.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_t(Date c_t) {
        this.c_t = c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.ntype
     *
     * @return the value of en_news.ntype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Short getN_t_y() {
        return n_t_y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.ntype
     *
     * @param n_t_y the value for en_news.ntype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setN_t_y(Short n_t_y) {
        this.n_t_y = n_t_y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.diid
     *
     * @return the value of en_news.diid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Short getD_i_i() {
        return d_i_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.diid
     *
     * @param d_i_i the value for en_news.diid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setD_i_i(Short d_i_i) {
        this.d_i_i = d_i_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.district
     *
     * @return the value of en_news.district
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getD_i_s() {
        return d_i_s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.district
     *
     * @param d_i_s the value for en_news.district
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setD_i_s(String d_i_s) {
        this.d_i_s = d_i_s == null ? null : d_i_s.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.isdel
     *
     * @return the value of en_news.isdel
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Byte getI_s_d() {
        return i_s_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.isdel
     *
     * @param i_s_d the value for en_news.isdel
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setI_s_d(Byte i_s_d) {
        this.i_s_d = i_s_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_news.content
     *
     * @return the value of en_news.content
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getC_o_n() {
        return c_o_n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_news.content
     *
     * @param c_o_n the value for en_news.content
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_o_n(String c_o_n) {
        this.c_o_n = c_o_n == null ? null : c_o_n.trim();
    }
}