package com.en.room.entity;


public class PicInfo extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_pic_info.rpiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer r_p_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_pic_info.rbiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer r_b_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_pic_info.url
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String u_r_l;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_pic_info.rptype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Byte r_p_t;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_pic_info.rpiid
     *
     * @return the value of en_room_pic_info.rpiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getR_p_i() {
        return r_p_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_pic_info.rpiid
     *
     * @param r_p_i the value for en_room_pic_info.rpiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setR_p_i(Integer r_p_i) {
        this.r_p_i = r_p_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_pic_info.rbiid
     *
     * @return the value of en_room_pic_info.rbiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getR_b_i() {
        return r_b_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_pic_info.rbiid
     *
     * @param r_b_i the value for en_room_pic_info.rbiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setR_b_i(Integer r_b_i) {
        this.r_b_i = r_b_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_pic_info.url
     *
     * @return the value of en_room_pic_info.url
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getU_r_l() {
        return u_r_l;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_pic_info.url
     *
     * @param u_r_l the value for en_room_pic_info.url
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setU_r_l(String u_r_l) {
        this.u_r_l = u_r_l == null ? null : u_r_l.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_pic_info.rptype
     *
     * @return the value of en_room_pic_info.rptype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Byte getR_p_t() {
        return r_p_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_pic_info.rptype
     *
     * @param r_p_t the value for en_room_pic_info.rptype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setR_p_t(Byte r_p_t) {
        this.r_p_t = r_p_t;
    }
}