package com.en.room.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RoomBaseInfo extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.rbiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer r_b_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.cdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer c_d_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.ccid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer c_c_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.sdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer s_d_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.amount
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private BigDecimal a_m_o;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.apartmentname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String a_m_n_a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.apartmentaddress
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String a_m_a_d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.days
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String d_a_s;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.introduce
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String i_n_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.atype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Byte a_t_y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.preferential
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String p_r_e;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date c_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.geohash
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String g_e_o;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.lid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer l_i_d;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.lng
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Double l_n_g;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_room_base_info.lat
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Double l_a_t;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.rbiid
     *
     * @return the value of en_room_base_info.rbiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getR_b_i() {
        return r_b_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.rbiid
     *
     * @param r_b_i the value for en_room_base_info.rbiid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setR_b_i(Integer r_b_i) {
        this.r_b_i = r_b_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.cdid
     *
     * @return the value of en_room_base_info.cdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getC_d_i() {
        return c_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.cdid
     *
     * @param c_d_i the value for en_room_base_info.cdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_d_i(Integer c_d_i) {
        this.c_d_i = c_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.ccid
     *
     * @return the value of en_room_base_info.ccid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getC_c_i() {
        return c_c_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.ccid
     *
     * @param c_c_i the value for en_room_base_info.ccid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_c_i(Integer c_c_i) {
        this.c_c_i = c_c_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.sdid
     *
     * @return the value of en_room_base_info.sdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getS_d_i() {
        return s_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.sdid
     *
     * @param s_d_i the value for en_room_base_info.sdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setS_d_i(Integer s_d_i) {
        this.s_d_i = s_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.amount
     *
     * @return the value of en_room_base_info.amount
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public BigDecimal getA_m_o() {
        return a_m_o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.amount
     *
     * @param a_m_o the value for en_room_base_info.amount
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_m_o(BigDecimal a_m_o) {
        this.a_m_o = a_m_o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.apartmentname
     *
     * @return the value of en_room_base_info.apartmentname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getA_m_n_a() {
        return a_m_n_a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.apartmentname
     *
     * @param a_m_n_a the value for en_room_base_info.apartmentname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_m_n_a(String a_m_n_a) {
        this.a_m_n_a = a_m_n_a == null ? null : a_m_n_a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.apartmentaddress
     *
     * @return the value of en_room_base_info.apartmentaddress
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getA_m_a_d() {
        return a_m_a_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.apartmentaddress
     *
     * @param a_m_a_d the value for en_room_base_info.apartmentaddress
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_m_a_d(String a_m_a_d) {
        this.a_m_a_d = a_m_a_d == null ? null : a_m_a_d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.days
     *
     * @return the value of en_room_base_info.days
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getD_a_s() {
        return d_a_s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.days
     *
     * @param d_a_s the value for en_room_base_info.days
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setD_a_s(String d_a_s) {
        this.d_a_s = d_a_s == null ? null : d_a_s.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.introduce
     *
     * @return the value of en_room_base_info.introduce
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getI_n_t() {
        return i_n_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.introduce
     *
     * @param i_n_t the value for en_room_base_info.introduce
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setI_n_t(String i_n_t) {
        this.i_n_t = i_n_t == null ? null : i_n_t.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.atype
     *
     * @return the value of en_room_base_info.atype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Byte getA_t_y() {
        return a_t_y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.atype
     *
     * @param a_t_y the value for en_room_base_info.atype
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setA_t_y(Byte a_t_y) {
        this.a_t_y = a_t_y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.preferential
     *
     * @return the value of en_room_base_info.preferential
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getP_r_e() {
        return p_r_e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.preferential
     *
     * @param p_r_e the value for en_room_base_info.preferential
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setP_r_e(String p_r_e) {
        this.p_r_e = p_r_e == null ? null : p_r_e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.ctime
     *
     * @return the value of en_room_base_info.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getC_t() {
        return c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.ctime
     *
     * @param c_t the value for en_room_base_info.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_t(Date c_t) {
        this.c_t = c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.geohash
     *
     * @return the value of en_room_base_info.geohash
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getG_e_o() {
        return g_e_o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.geohash
     *
     * @param g_e_o the value for en_room_base_info.geohash
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setG_e_o(String g_e_o) {
        this.g_e_o = g_e_o == null ? null : g_e_o.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.lid
     *
     * @return the value of en_room_base_info.lid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getL_i_d() {
        return l_i_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.lid
     *
     * @param l_i_d the value for en_room_base_info.lid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_i_d(Integer l_i_d) {
        this.l_i_d = l_i_d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.lng
     *
     * @return the value of en_room_base_info.lng
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Double getL_n_g() {
        return l_n_g;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.lng
     *
     * @param l_n_g the value for en_room_base_info.lng
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_n_g(Double l_n_g) {
        this.l_n_g = l_n_g;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_room_base_info.lat
     *
     * @return the value of en_room_base_info.lat
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Double getL_a_t() {
        return l_a_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_room_base_info.lat
     *
     * @param l_a_t the value for en_room_base_info.lat
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setL_a_t(Double l_a_t) {
        this.l_a_t = l_a_t;
    }
}