package com.en.room.entity;


public class SchoolDic extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_school_dic.sdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer s_d_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_school_dic.cdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer c_d_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_school_dic.scname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String s_c_n;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_school_dic.sdid
     *
     * @return the value of en_school_dic.sdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getS_d_i() {
        return s_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_school_dic.sdid
     *
     * @param s_d_i the value for en_school_dic.sdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setS_d_i(Integer s_d_i) {
        this.s_d_i = s_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_school_dic.cdid
     *
     * @return the value of en_school_dic.cdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getC_d_i() {
        return c_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_school_dic.cdid
     *
     * @param c_d_i the value for en_school_dic.cdid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_d_i(Integer c_d_i) {
        this.c_d_i = c_d_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_school_dic.scname
     *
     * @return the value of en_school_dic.scname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getS_c_n() {
        return s_c_n;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_school_dic.scname
     *
     * @param s_c_n the value for en_school_dic.scname
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setS_c_n(String s_c_n) {
        this.s_c_n = s_c_n == null ? null : s_c_n.trim();
    }
}