package com.en.room.entity;

import java.util.Date;

public class VerificationCode extends BaseVo {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_verification_code.vcid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Integer v_c_i;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_verification_code.phone
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String p_h_o;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_verification_code.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private Date c_t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column en_verification_code.vcode
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    private String v_c;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_verification_code.vcid
     *
     * @return the value of en_verification_code.vcid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Integer getV_c_i() {
        return v_c_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_verification_code.vcid
     *
     * @param v_c_i the value for en_verification_code.vcid
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setV_c_i(Integer v_c_i) {
        this.v_c_i = v_c_i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_verification_code.phone
     *
     * @return the value of en_verification_code.phone
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getP_h_o() {
        return p_h_o;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_verification_code.phone
     *
     * @param p_h_o the value for en_verification_code.phone
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setP_h_o(String p_h_o) {
        this.p_h_o = p_h_o == null ? null : p_h_o.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_verification_code.ctime
     *
     * @return the value of en_verification_code.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public Date getC_t() {
        return c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_verification_code.ctime
     *
     * @param c_t the value for en_verification_code.ctime
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setC_t(Date c_t) {
        this.c_t = c_t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column en_verification_code.vcode
     *
     * @return the value of en_verification_code.vcode
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public String getV_c() {
        return v_c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column en_verification_code.vcode
     *
     * @param v_c the value for en_verification_code.vcode
     *
     * @mbggenerated Fri Feb 19 16:45:13 CST 2016
     */
    public void setV_c(String v_c) {
        this.v_c = v_c == null ? null : v_c.trim();
    }
}